newsletter/config/urls.py
from django.urls import path

from . import views

app_name = "config"

urlpatterns = [
    path("", views.index, name="index"),
    path("queue", views.view_queues, name="view_queues"),
    path("queue/create/", views.create_queue, name="create_queue"),
    path("queue/<int:queue_id>/delete/", views.delete_queue, name="delete_queue"),
    path(
        "email/<int:email_id>/delete/",
        views.delete_processed_email,
        name="delete_processed_email",
    ),
]

newsletter/newsletter/urls.py
from django.contrib.auth import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("config.urls", namespace="config")),
    path("admin/", admin.site.urls),
    path("", include("social_django.urls", namespace="social")),
    path("accounts/", include("django.contrib.auth.urls")),
]

newsletter/config/models.py
from django.db import models
from django.contrib.auth.models import User


class QueueFilter(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    queue_name = models.CharField(max_length=256, blank=False, null=False)
    label_id = models.CharField(max_length=256, blank=False, null=False)

    def __str__(self):
        return f"{self.owner} - {self.queue_name}"


class ProcessedEmail(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    email_id = models.CharField(max_length=256, blank=False, null=False)
    subject = models.CharField(max_length=256, blank=False, null=False)
    sent_to = models.ForeignKey(QueueFilter, on_delete=models.CASCADE)
    processed_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.subject}"

newsletter/config/views.py
import pika
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from .gmail_api import get_labels
from .models import QueueFilter, ProcessedEmail


def index(request):
    return render(request, "config/index.html")


@login_required
def view_queues(request):
    labels = get_labels(request.user)
    queues = QueueFilter.objects.filter(owner=request.user)
    processed_emails = ProcessedEmail.objects.filter(owner=request.user).order_by(
        "-processed_on"
    )[:5]
    return render(
        request,
        "config/queues.html",
        context={
            "labels": labels,
            "queues": queues,
            "processed_emails": processed_emails,
        },
    )


@login_required
def create_queue(request):
    if not request.user.has_perm("config.add_queue_filter"):
        raise PermissionDenied

    if request.method == "POST":
        label_id = request.POST.get("label_id")
        queue_name = request.POST.get("queue_name")
        if QueueFilter.objects.filter(label_id=label_id).exists():
            messages.add_message(request, messages.ERROR, "Queue already exists")
            return redirect("config:view_queues")

        queue = QueueFilter(
            owner=request.user, label_id=label_id, queue_name=queue_name
        )
        queue.save()

        credentials = pika.PlainCredentials("guest", "guest")
        connection = pika.BlockingConnection(
            pika.ConnectionParameters(
                host="192.168.0.55",
                port=5672,
                virtual_host="/",
                credentials=credentials,
            )
        )
        channel = connection.channel()
        channel.queue_declare(queue=queue_name, durable=True)
        connection.close()

        messages.add_message(request, messages.SUCCESS, f"Queue {queue_name} created!")
        return redirect("config:view_queues")


@login_required
def delete_queue(request, queue_id):
    if not request.user.has_perm("config.delete_queue_filter"):
        raise PermissionDenied

    queue = QueueFilter.objects.get(id=queue_id)
    queue.delete()

    messages.add_message(
        request, messages.SUCCESS, f"Queue {queue.queue_name} deleted!"
    )
    return redirect("config:view_queues")


@login_required
def delete_processed_email(request, email_id):
    if not request.user.has_perm("config.delete_processed_email"):
        raise PermissionDenied

    email = ProcessedEmail.objects.get(id=email_id)
    email.delete()

    messages.add_message(
        request, messages.INFO, f"Email {email.subject} will be reprocessed"
    )
    return redirect("config:view_queues")

newsletter/config/templates/config/index.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row">
    <h3>Newsletter Webapp</h3>
</div>
{% endblock %}

newsletter/config/templates/config/labels.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row">
    <h5>Labels</h5>
</div>
<div class="row">
<form action="{% url 'config:create_filters' %}" method=POST>
    {% csrf_token %}
    {% for label in labels %}
    <div class="form-group form-check">
        <input id="checkbox{{ loop.index }}" class="form-check-input" name="filters[]" value="{{ label.id }}" type="checkbox" {% if label.id in existing_filters %} checked {% endif %}>{{ label.name }}</input><br>
    </div>
    {% endfor %}
    <input class="btn btn-primary" type="submit" value="Add Filters">
</form>
</div>
{% endblock %}

newsletter/config/templates/config/queues.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row">
    <div class="col">
        <h3>Config</h3>
    </div>
</div>
<div class="row">
    <div class="col-4">
        <h5>Existing Queues</h5>
        {% if queues %}
        {% for queue in queues %}
        <p>{{ queue.queue_name }}{% if perms.config.delete_queue_filter %} | <a href="{% url 'config:delete_queue' queue.id %}">[x]</a>{% endif %}</p>
        {% endfor %}
        {% else %}
        <p>No queues found</p>
        {% endif %}
    </div>
    <div class="col">
        <h5>Last 5 Emails</h5>
        <table class="table table-striped">
            <thead>
                <tr>
                  <th scope="col">Subject</th>
                  <th scope="col">Queue</th>
                  <th scope="col">Processed On</th>
                  <th scope="col">Reprocess</th>
                </tr>
            </thead>
            <tbody>
                {% for email in processed_emails %}
                <tr>
                    <th>{{ email.subject }}</th>
                    <th>{{ email.sent_to.queue_name }}</th>
                    <th>{{ email.processed_on }}</th>
                    <th><a href="{% url 'config:delete_processed_email' email.id %}">Reprocess</a></th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% if perms.config.add_queue_filter %}
<div class="row">
    <div class="col">
        <h5>Create a Queue</h5>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="{% url 'config:create_queue' %}" method=POST>
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label" for="label_id">Label Name</label>
                <select name="label_id" class="form-control">
                {% for label in labels %}
                    <option value="{{ label.id }}">{{ label.name }}</option>
                {% endfor %}
            </select>
            </div>
            <div class="form-group">
                <label class="form-label" for="queue_name">Queue Name</label>
                <input name="queue_name" class="form-control" type="text">
            </div>
            <input class="btn btn-primary" type="submit" value="Add Filters">
        </form>
    </div>
</div>
{% else %}
<div class="row">
    <div class="col">
        <h5>No permissions</h5>
    </div>
</div>
{% endif %}
{% endblock %}

newsletter/config/templates/config/test.html
{% extends 'newsletter/base.html' %}
{% block content %}
<h3>Testing</h3>
{{ emails }}
{% endblock %}

newsletter/templates/newsletter/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Newsletter Webapp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'config:index' %}">Newsletter</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'config:view_queues' %}">Queues</a>
          </li>
        </ul>
        <div class="form-inline my-2 my-lg-0">
            {% if request.user.is_authenticated %}
            <span class="text-light">{{ request.user }} | <a href="{% url 'logout' %}" class="text-light">Logout</a>{% if request.user.is_superuser %} | <a href="{% url 'admin:index' %}" class="text-light">Admin</a>{% endif %}</span>
            {% else %}
                <a href="{% url 'social:begin' 'google-oauth2' %}" class="text-light">Log In</a>
            {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
        {% if messages %}
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert">
                    {% elif message.tags == 'success' %}
                        <div class="alert alert-success" role="alert">
                    {% else %}
                        <div class="alert alert-primary" role="alert">
                    {% endif %}
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    {% block content %}
    {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>